import { supabase } from '@/lib/supabase';
import { can } from '@/lib/permissions';
import { roleLabel } from '@/lib/office-utils';
import { trpcClient } from '@/lib/trpc';
import PlatformPages from '@/components/PlatformPages';
import DashboardOverview, { type PendingContract, type PendingRun } from '@/components/DashboardOverview';
import ResearchCenter from '@/components/ResearchCenter';
import ContractStudio from '@/components/ContractStudio';
import AgentsBoard from '@/components/AgentsBoard';
import CasesPage from '@/components/office/CasesPage';
import ClientsPage from '@/components/office/ClientsPage';
import SchedulePage from '@/components/office/SchedulePage';
import OfficePage from '@/components/office/OfficePage';
import CaseWorkspace from '@/components/office/CaseWorkspace';
import AppShell from '@/components/shell/AppShell';
import CommandPalette from '@/components/shell/CommandPalette';
import { Brand } from '@/components/shell/brand';
import type { Client, ClientCommunication, Hearing, LegalCase, LegalSource, Office, OfficeDocument, Profile, Task } from '@/components/office/types';
import type { Session } from '@supabase/supabase-js';
import { Bot, BookOpenText, BriefcaseBusiness, CalendarClock, ClipboardCheck, FileSignature, FileText, FolderKanban, LayoutDashboard, Loader2, LogOut, Menu, Scale, SearchCheck, UserPlus, Users, X } from 'lucide-react';
import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

type Page = 'dashboard' | 'cases' | 'schedule' | 'clients' | 'research' | 'contracts' | 'agents' | 'office';

const PAGE_PATHS: Record<Page, string> = {
  dashboard: '/', cases: '/cases', schedule: '/schedule', clients: '/clients',
  research: '/research', contracts: '/contracts', agents: '/agents', office: '/office',
};
function pathToPage(pathname: string): Page {
  const clean = ('/' + pathname.split('/').filter(Boolean).join('/'));
  const entry = (Object.entries(PAGE_PATHS) as Array<[Page, string]>).find(([, value]) => value === clean);
  return entry ? entry[0] : (clean.startsWith('/cases') ? 'cases' : clean.startsWith('/office') ? 'office' : 'dashboard');
}


const inputClass = 'w-full h-10 rounded-lg border bg-background px-3 text-sm';
const dateValue = (offset = 1) => new Date(Date.now() + offset * 86400000).toISOString().slice(0, 16);

function Empty({ icon: Icon, title, text, action }: { icon: typeof BriefcaseBusiness; title: string; text: string; action?: ReactNode }) { return <div className="border border-dashed rounded-2xl py-12 text-center bg-white/50"><div className="h-12 w-12 mx-auto grid place-items-center rounded-xl bg-[#edf4f1] text-[#1b6258]"><Icon className="h-6 w-6" /></div><p className="font-semibold mt-4 text-[#153a36]">{title}</p><p className="text-sm text-muted-foreground mt-1 px-5">{text}</p>{action && <div className="mt-5">{action}</div>}</div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 bg-[#092a26]/45 backdrop-blur-sm z-50 p-4 grid place-items-center" dir="rtl"><Card className="w-full max-w-2xl max-h-[94vh] overflow-y-auto border-0 shadow-2xl"><CardHeader className="sticky top-0 bg-card/95 z-10 border-b"><div className="flex justify-between items-center"><CardTitle className="text-xl text-[#153a36]">{title}</CardTitle><button className="p-2 rounded-lg hover:bg-muted" onClick={onClose}><X className="h-4 w-4" /></button></div></CardHeader><CardContent className="pt-6">{children}</CardContent></Card></div>; }

function Login({ done }: { done: () => Promise<void> }) {
  const [isNew, setIsNew] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const { data, error } = isNew ? await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (error) return toast.error(error.message); if (isNew && !data.session) return toast.success('تم إنشاء الحساب. راجع بريدك لتأكيد التسجيل.'); await done(); toast.success('تم تسجيل الدخول.'); };
  return <main dir="rtl" className="min-h-screen w-full max-w-full overflow-x-hidden bg-[#f4f7f5] grid lg:grid-cols-2"><section className="hidden lg:flex min-w-0 bg-[#103b35] text-white p-14 relative overflow-hidden flex-col justify-between"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(circle at 15% 20%, #e8c377 0, transparent 23%),radial-gradient(circle at 80% 80%, #67a99c 0, transparent 30%)' }} /><div className="relative"><Brand /><div className="mt-32 max-w-xl"><p className="text-[#e8c377]">منظومة عربية لمكاتب المحاماة في قطر</p><h1 className="text-5xl leading-tight font-bold mt-4">كل قضية في مسار واضح، وكل مذكرة مسنودة بمصدر.</h1><p className="text-emerald-50/80 mt-6 leading-8">إدارة القضايا والجلسات والعملاء والمستندات وفريق المكتب، مع مساحة ذكية لصياغة المذكرات ومراجعة مراجعها.</p></div></div><p className="relative text-sm text-emerald-50/70">صلاحيات متعددة الأدوار · عزل آمن للبيانات · مصادر قانونية موثقة</p></section><section className="grid min-w-0 place-items-center p-5"><div className="w-full max-w-md mx-auto min-w-0"><div className="lg:hidden mb-10"><Brand /></div><Card className="w-full min-w-0 border-0 shadow-xl shadow-[#0d3b36]/10"><CardHeader><CardTitle className="text-2xl text-[#153a36]">{isNew ? 'ابدأ مساحة مكتبك' : 'مرحباً بعودتك'}</CardTitle><CardDescription>{isNew ? 'أنشئ حسابك ثم جهّز بيانات المكتب.' : 'سجل الدخول للوصول إلى إدارة المكتب.'}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{isNew && <div className="space-y-2"><Label>الاسم الكامل</Label><Input value={name} onChange={e => setName(e.target.value)} required placeholder="الاسم الكامل" /></div>}<div className="space-y-2"><Label>البريد الإلكتروني</Label><Input dir="ltr" type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="name@office.qa" /></div><div className="space-y-2"><Label>كلمة المرور</Label><Input dir="ltr" type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} /></div><Button className="w-full h-11 bg-[#0d3b36] hover:bg-[#164d45]" disabled={busy}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{isNew ? 'إنشاء الحساب' : 'تسجيل الدخول'}</Button></form><p className="text-center text-sm text-muted-foreground mt-5">{isNew ? 'لديك حساب؟' : 'ليس لديك حساب؟'} <button className="font-semibold text-[#1b6258]" onClick={() => setIsNew(!isNew)}>{isNew ? 'تسجيل الدخول' : 'إنشاء حساب'}</button></p></CardContent></Card><p className="text-xs text-muted-foreground text-center mt-5 leading-5">النتائج القانونية المولدة هي مسودات للمراجعة المهنية وليست بديلاً عن المحامي المختص.</p></div></section></main>;
}

export default function Home() {
  const [session, setSession] = useState<Session | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [office, setOffice] = useState<Office | null>(null); const [isPlatformAdmin, setIsPlatformAdmin] = useState(false); const [ready, setReady] = useState(false); const [paletteOpen, setPaletteOpen] = useState(false); const [autoIntake, setAutoIntake] = useState(true); const [pendingIntake, setPendingIntake] = useState<string | null>(null); const [prefillCaseId, setPrefillCaseId] = useState(''); const [modal, setModal] = useState<'client' | 'case' | 'hearing' | 'task' | 'doc' | 'invite' | 'communication' | 'outcome' | null>(null);
  const [location, navigate] = useLocation();
  const page = pathToPage(location);
  const goToPage = (next: Page) => { navigate(PAGE_PATHS[next]); };
  const [contractDocs, setContractDocs] = useState<PendingContract[]>([]); const [agentRuns, setAgentRuns] = useState<PendingRun[]>([]);
  const [clients, setClients] = useState<Client[]>([]); const [communications, setCommunications] = useState<ClientCommunication[]>([]); const [selectedClientId, setSelectedClientId] = useState(''); const [selectedHearing, setSelectedHearing] = useState<Hearing | null>(null); const [cases, setCases] = useState<LegalCase[]>([]); const [hearings, setHearings] = useState<Hearing[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [docs, setDocs] = useState<OfficeDocument[]>([]); const [team, setTeam] = useState<Profile[]>([]); const [sources, setSources] = useState<LegalSource[]>([]);
  const load = async (incoming?: Session | null) => {
    const active = incoming ?? (await supabase.auth.getSession()).data.session; setSession(active ?? null); if (!active) { setProfile(null); setOffice(null); setIsPlatformAdmin(false); setReady(true); return; }
    setReady(false); const id = active.user.id; let { data: own } = await supabase.from('profiles').select('id,office_id,role,display_name,email,is_active').eq('id', id).maybeSingle(); if (!own) { await new Promise(resolve => setTimeout(resolve, 500)); ({ data: own } = await supabase.from('profiles').select('id,office_id,role,display_name,email,is_active').eq('id', id).maybeSingle()); }
    const { data: platformAdmin } = await supabase.from('platform_admins').select('user_id').eq('user_id', id).eq('is_active', true).maybeSingle(); setProfile(own as Profile | null); setIsPlatformAdmin(Boolean(platformAdmin)); if (platformAdmin) { setOffice(null); setReady(true); return; } if (!own?.office_id) { setOffice(null); setReady(true); return; } const all = await Promise.all([
      supabase.from('offices').select('id,name,phone,email').eq('id', own.office_id).single(), supabase.from('clients').select('id,full_name,kind,phone,email,national_id,notes,created_at').order('created_at', { ascending: false }),
      supabase.from('legal_cases').select('id,case_number,title,client_id,responsible_lawyer_id,type,status,court_name,opening_date,description').order('created_at', { ascending: false }), supabase.from('hearings').select('id,case_id,hearing_at,court_name,court_room,status,outcome,reminder_at').order('hearing_at'),
      supabase.from('tasks').select('id,title,description,assigned_to,priority,status,due_at,case_id').order('due_at'), supabase.from('documents').select('id,file_name,category,case_id,client_id,created_at').order('created_at', { ascending: false }),
      supabase.from('profiles').select('id,office_id,role,display_name,email,is_active').order('display_name'), supabase.from('legal_sources').select('id,title,official_number,source_type,source_url,issued_on').order('source_type').order('title'),
      supabase.from('client_communications').select('id,client_id,channel,subject,content,occurred_at,created_by').order('occurred_at', { ascending: false }),
      supabase.from('contract_documents').select('id,title,status,current_version,created_at').eq('status', 'in_review').order('created_at', { ascending: false }).limit(6),
      supabase.from('agent_runs').select('id,agent_type,status,objective,pending_action,created_at').eq('status', 'awaiting_approval').order('created_at', { ascending: false }).limit(6),
    ]); setOffice(all[0].data as Office | null); setClients((all[1].data ?? []) as Client[]); setCases((all[2].data ?? []) as LegalCase[]); setHearings((all[3].data ?? []) as Hearing[]); setTasks((all[4].data ?? []) as Task[]); setDocs((all[5].data ?? []) as OfficeDocument[]); setTeam((all[6].data ?? []) as Profile[]); setSources((all[7].data ?? []) as LegalSource[]); setCommunications((all[8].data ?? []) as ClientCommunication[]); setContractDocs((all[9].data ?? []) as PendingContract[]); setAgentRuns((all[10].data ?? []) as PendingRun[]); setReady(true);
  };
  useEffect(() => { load(); const { data } = supabase.auth.onAuthStateChange((_event, changed) => { setTimeout(() => load(changed), 0); }); return () => data.subscription.unsubscribe(); }, []);
  const manager = can(profile?.role, 'manage_office'); const practitioner = can(profile?.role, 'create_case');
  const caseById = (id?: string | null) => cases.find(item => item.id === id);
  const createOffice = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const { error } = await supabase.rpc('create_office_with_manager', { p_name: data.get('name') as string, p_phone: data.get('phone') || null, p_email: data.get('email') || null, p_address: null }); if (error) return toast.error(error.message); await load(); };
  const add = async (kind: NonNullable<typeof modal>, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!practitioner && ['client', 'case', 'hearing', 'task', 'doc'].includes(kind)) return toast.error('هذه العملية متاحة للمحامي ومدير المكتب فقط.'); if (kind === 'invite' && !manager) return toast.error('دعوات أعضاء المكتب متاحة لمدير المكتب فقط.'); const data = new FormData(event.currentTarget); let error: { message: string } | null = null;
    if (kind === 'client') ({ error } = await supabase.from('clients').insert({ office_id: profile!.office_id!, full_name: data.get('name') as string, kind: data.get('kind') as string, phone: data.get('phone') || null, email: data.get('email') || null, national_id: data.get('id_number') || null, notes: data.get('notes') || null, created_by: profile!.id }));
    let createdCaseId: string | null = null; let createdFiles = 0;
    if (kind === 'case') { const { data: createdCase, error: caseError } = await supabase.from('legal_cases').insert({ office_id: profile!.office_id!, case_number: data.get('number') as string, title: data.get('title') as string, client_id: data.get('client') as string, responsible_lawyer_id: data.get('lawyer') || profile!.id, type: data.get('type') as string, court_name: data.get('court') || null, opponent_name: data.get('opponent') || null, description: data.get('description') || null, created_by: profile!.id }).select('id').single(); error = caseError; createdCaseId = createdCase?.id ?? null;
      if (createdCaseId) { const papers = data.getAll('papers') as File[]; for (const paper of papers) { if (!paper.name) continue; const ext = paper.name.includes('.') ? '.' + paper.name.split('.').pop() : ''; const base = paper.name.slice(0, paper.name.length - ext.length).replace(/[^a-zA-Z0-9\-_]/g, ''); const safeBase = (base || 'file').slice(0, 60); const paperPath = `${profile!.office_id}/${Date.now()}-${safeBase}${ext}`; const paperUpload = await supabase.storage.from('legal-documents').upload(paperPath, paper, { contentType: paper.type }); if (paperUpload.error) { toast.error(paperUpload.error.message); continue; } const { error: paperError } = await supabase.from('documents').insert({ office_id: profile!.office_id!, file_name: paper.name, storage_path: paperPath, mime_type: paper.type || null, byte_size: paper.size, category: 'court_filing', case_id: createdCaseId, client_id: data.get('client') || null, uploaded_by: profile!.id }); if (!paperError) createdFiles++; } }
      const opponentName = (data.get('opponent') as string)?.trim();
      if (createdCaseId && opponentName && opponentName.length >= 2) {
        try {
          const conflict = await trpcClient.officeFeatures.checkConflict.mutate({ accessToken: session!.access_token, partyName: opponentName, caseId: createdCaseId });
          if (conflict.verdict === 'conflict') toast.warning('تنبيه: الطرف الخصم يطابق طرفاً في قضية أخرى بالمكتب — راجع فحص تعارض المصالح في ملف القضية.');
        } catch { /* الفحص لا يمنع التسجيل — تنبيه فقط */ }
      } }
    if (kind === 'hearing') { const at = new Date(data.get('at') as string); ({ error } = await supabase.from('hearings').insert({ office_id: profile!.office_id!, case_id: data.get('case') as string, hearing_at: at.toISOString(), court_name: data.get('court') || null, court_room: data.get('room') || null, hearing_type: data.get('type') || null, reminder_at: new Date(at.getTime() - 86400000).toISOString(), notes: data.get('notes') || null, created_by: profile!.id })); }
    if (kind === 'task') ({ error } = await supabase.from('tasks').insert({ office_id: profile!.office_id!, title: data.get('title') as string, description: data.get('description') || null, case_id: data.get('case') || null, assigned_to: data.get('member') || profile!.id, priority: data.get('priority') as string, due_at: data.get('due') ? new Date(data.get('due') as string).toISOString() : null, created_by: profile!.id }));
    if (kind === 'invite') { const { data: invitation, error: inviteError } = await supabase.from('office_invitations').upsert({ office_id: profile!.office_id!, email: data.get('email') as string, role: data.get('role') as string, created_by: profile!.id }, { onConflict: 'office_id,email' }).select('invitation_token').single(); error = inviteError; if (!error && invitation?.invitation_token) { await navigator.clipboard?.writeText(`${window.location.origin}/?invite=${invitation.invitation_token}`); toast.success('تم إنشاء رابط الدعوة ونسخه للحافظة.'); } else if (!error) { error = { message: 'تعذر إنشاء رابط الدعوة.' }; } }
    if (kind === 'doc') { const file = data.get('file') as File; if (!file?.name) return toast.error('اختر ملفاً أولاً.'); const ext = file.name.includes('.') ? '.' + file.name.split('.').pop() : '';
          const base = file.name.slice(0, file.name.length - ext.length).replace(/[^a-zA-Z0-9\-_]/g, '');
          const safeBase = (base || 'file').slice(0, 60);
          const path = `${profile!.office_id}/${Date.now()}-${safeBase}${ext}`; const upload = await supabase.storage.from('legal-documents').upload(path, file, { contentType: file.type }); if (upload.error) return toast.error(upload.error.message); ({ error } = await supabase.from('documents').insert({ office_id: profile!.office_id!, file_name: file.name, storage_path: path, mime_type: file.type || null, byte_size: file.size, category: data.get('category') as string, case_id: data.get('case') || null, client_id: data.get('client') || null, uploaded_by: profile!.id })); }
    if (error) return toast.error(error.message); setModal(null); await load(); toast.success(kind === 'case' ? (createdFiles > 0 ? `تم تسجيل القضية مع ${createdFiles} ورقة - يبدأ التحليل الذكي.` : 'تم تسجيل القضية.') : kind === 'task' ? 'تم إنشاء المهمة.' : 'تم الحفظ بنجاح.');
    if (kind === 'case' && createdCaseId) { if (autoIntake) setPendingIntake(createdCaseId); navigate(`/cases/${createdCaseId}`); }
  };
  const closeTask = async (task: Task) => { if (!(manager || task.assigned_to === profile?.id)) return toast.error('يمكنك إغلاق المهمة المسندة إليك فقط.'); const { error } = await supabase.from('tasks').update({ status: 'completed', completed_at: new Date().toISOString() }).eq('id', task.id); if (error) return toast.error(error.message); await load(); };
  const addCommunication = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const { error } = await supabase.from('client_communications').insert({ office_id: profile!.office_id!, client_id: data.get('client') as string, created_by: profile!.id, channel: data.get('channel') as string, subject: data.get('subject') as string, content: data.get('content') || null, occurred_at: new Date(data.get('occurred_at') as string).toISOString() }); if (error) return toast.error(error.message); setModal(null); await load(); toast.success('تم حفظ متابعة العميل.'); };
  const openCase = (caseId: string) => { navigate(`/cases/${caseId}`); };
  const openModalPlain = (kind: NonNullable<typeof modal>) => { setPrefillCaseId(''); setModal(kind); };

  const openHearingFor = (caseId: string) => { setPrefillCaseId(caseId); setModal('hearing'); };
  const openTaskFor = (caseId: string) => { setPrefillCaseId(caseId); setModal('task'); };
  const openDocFor = (caseId: string) => { setPrefillCaseId(caseId); setModal('doc'); };
  const recordOutcome = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!practitioner) return toast.error('تسجيل نتيجة الجلسة متاح للمحامي ومدير المكتب فقط.'); if (!selectedHearing) return; const data = new FormData(event.currentTarget); const { error } = await supabase.from('hearings').update({ status: data.get('status') as string, outcome: data.get('outcome') as string }).eq('id', selectedHearing.id); if (error) return toast.error(error.message); setModal(null); setSelectedHearing(null); await load(); toast.success('تم تحديث نتيجة الجلسة.'); };
  if (!ready) return <main className="min-h-screen grid place-items-center bg-[#f4f7f5]"><Loader2 className="animate-spin text-[#1b6258]" /></main>;
  if (!session) return <Login done={() => load()} />;
  if (isPlatformAdmin) {
    const segment = location.split('/').filter(Boolean).at(-1);
    const section = (['overview', 'offices', 'invoices', 'recurring', 'users', 'audit', 'alerts', 'plans', 'analytics', 'support', 'brand'] as const).includes(segment as 'overview') ? segment as 'overview' | 'offices' | 'invoices' | 'recurring' | 'users' | 'audit' | 'alerts' | 'plans' | 'analytics' | 'support' | 'brand' : 'overview';
    return <PlatformPages adminId={session.user.id} section={section} />;
  }
  if (!profile) return <main className="min-h-screen grid place-items-center"><Loader2 className="animate-spin" /></main>;
  if (!office) { const invitationToken = new URLSearchParams(window.location.search).get('invite'); const acceptInvitation = async () => { if (!invitationToken) return; const { error } = await supabase.rpc('accept_office_invitation', { p_token: invitationToken }); if (error) return toast.error(error.message); window.history.replaceState({}, '', window.location.pathname); await load(); toast.success('تم الانضمام إلى المكتب بنجاح.'); }; return <main dir="rtl" className="min-h-screen bg-[#f4f7f5] grid place-items-center p-5"><Card className="w-full max-w-xl border-0 shadow-xl"><CardHeader><Brand /><CardTitle className="text-2xl mt-7 text-[#153a36]">{invitationToken ? 'دعوة للانضمام إلى المكتب' : 'لنجهز مساحة مكتبك'}</CardTitle><CardDescription>{invitationToken ? 'سيتم تعيينك تلقائياً بالدور المحدد في الدعوة، ولا يمكنك تعديله من هذا الرابط.' : 'ستكون مدير المكتب ويمكنك بعد ذلك دعوة المحامين والموظفين.'}</CardDescription></CardHeader><CardContent>{invitationToken ? <div className="space-y-4"><div className="p-4 rounded-xl bg-[#edf4f1] text-sm leading-6 text-[#1b6258]">تحقق من أن هذا الحساب هو الحساب المقصود بالدعوة ثم أكمل الانضمام. سيُسجل الدور وفق صلاحية مدير المكتب.</div><Button onClick={acceptInvitation} className="w-full h-11 bg-[#0d3b36]">قبول الدعوة والانضمام</Button><div className="border-t pt-4"><p className="text-xs text-muted-foreground mb-3">لست مدعواً إلى مكتب؟ يمكنك إنشاء مكتب جديد بصفتك مديراً.</p><form onSubmit={createOffice} className="grid sm:grid-cols-2 gap-4"><div className="sm:col-span-2 space-y-2"><Label>اسم المكتب</Label><Input name="name" required placeholder="مكتب ... للمحاماة" /></div><div className="space-y-2"><Label>الهاتف</Label><Input name="phone" dir="ltr" /></div><div className="space-y-2"><Label>بريد المكتب</Label><Input name="email" dir="ltr" type="email" /></div><Button className="sm:col-span-2 h-11" variant="outline">إنشاء مكتب جديد</Button></form></div></div> : <form onSubmit={createOffice} className="grid sm:grid-cols-2 gap-4"><div className="sm:col-span-2 space-y-2"><Label>اسم المكتب</Label><Input name="name" required placeholder="مكتب ... للمحاماة" /></div><div className="space-y-2"><Label>الهاتف</Label><Input name="phone" dir="ltr" /></div><div className="space-y-2"><Label>بريد المكتب</Label><Input name="email" dir="ltr" type="email" /></div><Button className="sm:col-span-2 h-11 bg-[#0d3b36]">إنشاء المكتب</Button></form>}</CardContent></Card></main>; }
  const openCaseId = location.startsWith('/cases/') ? location.slice('/cases/'.length) : null;
  const openCaseItem = openCaseId ? cases.find(item => item.id === openCaseId) : null;
  const officeTab = location.startsWith('/office/') && ['team', 'archive', 'reports', 'sources', 'notifications', 'audit'].includes(location.split('/')[2]) ? location.split('/')[2] as 'team' | 'archive' | 'reports' | 'sources' | 'notifications' | 'audit' : undefined;
  const prefillCase = prefillCaseId ? cases.find(item => item.id === prefillCaseId) : null;
  const prefillClientId = prefillCase?.client_id ?? '';
  const prefillClientName = prefillClientId ? clients.find(item => item.id === prefillClientId)?.full_name : null;

  const content: Record<Page, ReactNode> = {
    dashboard: <DashboardOverview accessToken={session.access_token} profile={profile} officeName={office.name} cases={cases} clients={clients} hearings={hearings} tasks={tasks} team={team} communications={communications} contractDocs={contractDocs} agentRuns={agentRuns} practitioner={practitioner} manager={manager} setPage={goToPage} openModal={openModalPlain} onRecordOutcome={hearing => { setSelectedHearing(hearing); setModal('outcome'); }} onCloseTask={closeTask} onRefresh={() => load()} onOpenCase={openCase} />,
    cases: <CasesPage cases={cases} clients={clients} team={team} practitioner={practitioner} onNewCase={() => openModalPlain('case')} onOpenCase={openCase} />,
    schedule: <SchedulePage hearings={hearings} tasks={tasks} cases={cases} team={team} practitioner={practitioner} manager={manager} profileId={profile.id} onRecordOutcome={hearing => { setSelectedHearing(hearing); setModal('outcome'); }} onCloseTask={closeTask} onOpenCase={openCase} />,
    clients: <ClientsPage clients={clients} cases={cases} communications={communications} practitioner={practitioner} onNewClient={() => openModalPlain('client')} onAddCommunication={clientId => { setSelectedClientId(clientId); setModal('communication'); }} />,
    office: <OfficePage initialTab={officeTab} team={team} cases={cases} clients={clients} tasks={tasks} hearings={hearings} documents={docs} sources={sources} practitioner={practitioner} manager={manager} accessToken={session.access_token} onInvite={() => openModalPlain('invite')} onUpload={() => openModalPlain('doc')} />,
    research: <ResearchCenter accessToken={session.access_token} cases={cases.map(item => ({ id: item.id, case_number: item.case_number, title: item.title }))} canUse={practitioner} canManage={manager} officeId={office.id} />,
    contracts: <ContractStudio accessToken={session.access_token} cases={cases.map(item => ({ id: item.id, case_number: item.case_number, title: item.title }))} clients={clients.map(item => ({ id: item.id, full_name: item.full_name }))} canUse={practitioner} />,
    agents: <AgentsBoard accessToken={session.access_token} cases={cases.map(item => ({ id: item.id, case_number: item.case_number, title: item.title }))} canUse={practitioner} />,
  };
  return <AppShell profile={profile} page={page} onNavigate={goToPage} onOpenPalette={() => setPaletteOpen(true)}>
    {content[page]}
    {openCaseItem && <CaseWorkspace caseItem={openCaseItem} clients={clients} team={team} hearings={hearings} tasks={tasks} documents={docs} accessToken={session.access_token} officeId={office.id} autoAnalyze={pendingIntake === openCaseId} onAutoAnalyzeDone={() => setPendingIntake(null)} practitioner={practitioner} manager={manager} profileId={profile.id} onClose={() => navigate('/cases')} onScheduleHearing={openHearingFor} onNewTask={openTaskFor} onUploadDoc={openDocFor} onRefresh={() => load()} />}
    <CommandPalette open={paletteOpen} onClose={() => setPaletteOpen(false)} cases={cases} clients={clients} hearings={hearings} tasks={tasks} documents={docs} canCreate={practitioner} onNavigate={goToPage} onOpenCase={openCase} onAction={kind => openModalPlain(kind)} />

{modal === 'client' && <Modal title="إضافة عميل" onClose={() => setModal(null)}><form className="grid sm:grid-cols-2 gap-4" onSubmit={e => add('client', e)}><div className="sm:col-span-2 space-y-2"><Label>الاسم أو اسم الشركة</Label><Input name="name" required /></div><div className="space-y-2"><Label>النوع</Label><select name="kind" className={inputClass}><option value="individual">فرد</option><option value="company">شركة</option></select></div><div className="space-y-2"><Label>رقم الهوية / السجل</Label><Input name="id_number" /></div><div className="space-y-2"><Label>الهاتف</Label><Input name="phone" dir="ltr" /></div><div className="space-y-2"><Label>البريد</Label><Input name="email" dir="ltr" type="email" /></div><div className="sm:col-span-2 space-y-2"><Label>ملاحظات</Label><Textarea name="notes" /></div><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">حفظ العميل</Button></div></form></Modal>}
  {modal === 'communication' && <Modal title="إضافة متابعة للعميل" onClose={() => setModal(null)}><form className="grid sm:grid-cols-2 gap-4" onSubmit={addCommunication}><div className="sm:col-span-2 space-y-2"><Label>العميل</Label><select name="client" className={inputClass} defaultValue={selectedClientId} required>{clients.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></div><div className="space-y-2"><Label>نوع التواصل</Label><select name="channel" className={inputClass} defaultValue="phone"><option value="phone">اتصال هاتفي</option><option value="email">بريد إلكتروني</option><option value="meeting">اجتماع</option><option value="whatsapp">واتساب</option><option value="other">أخرى</option></select></div><div className="space-y-2"><Label>وقت المتابعة</Label><Input name="occurred_at" type="datetime-local" defaultValue={dateValue(0)} required /></div><div className="sm:col-span-2 space-y-2"><Label>موضوع المتابعة</Label><Input name="subject" required placeholder="مثال: مراجعة المستندات المطلوبة" /></div><div className="sm:col-span-2 space-y-2"><Label>تفاصيل وإجراء لاحق</Label><Textarea name="content" className="min-h-28" placeholder="ما الذي تم التواصل بشأنه؟ وما الإجراء التالي؟" /></div><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">حفظ المتابعة</Button></div></form></Modal>}
  {modal === 'case' && <Modal title="تسجيل قضية جديدة" onClose={() => setModal(null)}>{clients.length ? <form className="grid sm:grid-cols-2 gap-4" onSubmit={e => add('case', e)}><div className="space-y-2"><Label>رقم القضية</Label><Input name="number" required placeholder="2026/1234" /></div><div className="space-y-2"><Label>النوع</Label><select name="type" className={inputClass}><option value="civil">مدنية</option><option value="commercial">تجارية</option><option value="criminal">جنائية</option><option value="labor">عمالية</option><option value="family">أسرة</option><option value="administrative">إدارية</option><option value="other">أخرى</option></select></div><div className="sm:col-span-2 space-y-2"><Label>عنوان القضية</Label><Input name="title" required /></div><div className="space-y-2"><Label>العميل</Label><select name="client" className={inputClass} required><option value="">اختر العميل</option>{clients.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></div><div className="space-y-2"><Label>المحامي المسؤول</Label><select name="lawyer" className={inputClass} defaultValue={profile.id}>{team.filter(i => ['manager', 'lawyer'].includes(i.role)).map(item => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></div><div className="space-y-2"><Label>المحكمة</Label><Input name="court" /></div><div className="sm:col-span-2 space-y-2"><Label>الطرف الخصم (يُفحص تلقائياً ضد تعارض المصالح)</Label><Input name="opponent" placeholder="اسم الخصم أو الشركة المدعى عليها" /></div><div className="sm:col-span-2 space-y-2"><Label>ملخص الوقائع</Label><Textarea name="description" /></div>
            <div className="sm:col-span-2 space-y-2"><Label>أوراق القضية (صحيفة الدعوى ومرفقاتها)</Label><Input name="papers" type="file" multiple accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" /><p className="text-[11px] text-muted-foreground leading-5">الصور (PNG/JPG) تُقرأ بالذكاء البصري عند استخدام OpenAI، ونصوص PDF/Word تُستخرج وتُحلل دائماً — كلها تُؤرشف في ملف القضية.</p></div>
            <div className="sm:col-span-2 space-y-2"><Label>ملاحظات إضافية للتحليل (اختياري)</Label><Textarea name="intakeNotes" className="min-h-20" placeholder="نقاط من المحامي: موقف الموكل، طلبات الخصم، ما يقلقك في الملف…" /></div>
            <label className="sm:col-span-2 flex items-center gap-2.5 rounded-xl border border-[#e5ece9] bg-[#f4f7f5] p-3 cursor-pointer"><input type="checkbox" checked={autoIntake} onChange={e => setAutoIntake(e.target.checked)} className="h-4 w-4 accent-[#0d3b36]" /><span className="text-sm font-semibold text-[#153a36]">شغّل التحليل الافتتاحي الذكي بعد الحفظ</span><span className="text-[11px] text-muted-foreground mr-auto">قوانين + دفوع + ثغرات + مسودة مذكرة</span></label><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">تسجيل القضية</Button></div></form> : <Empty icon={Users} title="يلزم إضافة عميل أولاً" text="القضية يجب أن ترتبط بعميل محفوظ في النظام." action={<Button onClick={() => { setModal(null); goToPage('clients'); }}>الانتقال إلى العملاء</Button>} />}</Modal>}
  {modal === 'hearing' && <Modal title="جدولة جلسة" onClose={() => setModal(null)}>{cases.length ? <form className="grid sm:grid-cols-2 gap-4" onSubmit={e => add('hearing', e)}>{prefillCase ? (<>
            <input type="hidden" name="case" value={prefillCase.id} />
            <div className="sm:col-span-2 space-y-2"><Label>القضية</Label><div className="h-10 rounded-lg bg-[#edf4f1] text-[#1b6258] px-3 flex items-center gap-2 text-sm font-semibold"><span className="truncate">{prefillCase.case_number} — {prefillCase.title}</span><span className="mr-auto text-[11px] font-normal shrink-0">مرتبطة تلقائياً بملف القضية</span></div></div>
            </>) : (<div className="sm:col-span-2 space-y-2"><Label>القضية</Label><select name="case" className={inputClass} defaultValue={prefillCaseId} required><option value="">اختر القضية</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} — {item.title}</option>)}</select></div>)}<div className="space-y-2"><Label>موعد الجلسة</Label><Input name="at" type="datetime-local" defaultValue={dateValue()} required /></div><div className="space-y-2"><Label>نوع الجلسة</Label><Input name="type" placeholder="مرافعة / تأجيل" /></div><div className="space-y-2"><Label>المحكمة</Label><Input name="court" /></div><div className="space-y-2"><Label>القاعة</Label><Input name="room" /></div><div className="sm:col-span-2 space-y-2"><Label>ملاحظات</Label><Textarea name="notes" /></div><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">حفظ الجلسة</Button></div></form> : <Empty icon={BriefcaseBusiness} title="يلزم تسجيل قضية أولاً" text="الجلسات تُدار في سياق قضية مرتبطة." />}</Modal>}
  {modal === 'outcome' && selectedHearing && <Modal title="تسجيل نتيجة الجلسة" onClose={() => { setModal(null); setSelectedHearing(null); }}><form className="space-y-4" onSubmit={recordOutcome}><div className="rounded-xl bg-[#f4f7f5] p-3 text-sm"><p className="font-semibold text-[#153a36]">{caseById(selectedHearing.case_id)?.title || 'قضية مرتبطة'}</p><p className="text-xs text-muted-foreground mt-1">{selectedHearing.hearing_at}</p></div><div className="space-y-2"><Label>حالة الجلسة</Label><select name="status" className={inputClass} defaultValue="held"><option value="held">عُقدت</option><option value="postponed">أُجلت</option><option value="cancelled">أُلغيت</option></select></div><div className="space-y-2"><Label>النتيجة أو القرار</Label><Textarea name="outcome" required className="min-h-32" placeholder="سجل ما حدث في الجلسة والإجراء المطلوب تالياً…" /></div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => { setModal(null); setSelectedHearing(null); }}>إلغاء</Button><Button className="bg-[#0d3b36]">حفظ النتيجة</Button></div></form></Modal>}
  {modal === 'task' && <Modal title="إنشاء مهمة" onClose={() => setModal(null)}><form className="grid sm:grid-cols-2 gap-4" onSubmit={e => add('task', e)}><div className="sm:col-span-2 space-y-2"><Label>عنوان المهمة</Label><Input name="title" required /></div><div className="space-y-2"><Label>إسناد إلى</Label><select name="member" className={inputClass} defaultValue={profile.id}>{team.map(item => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></div><div className="space-y-2"><Label>الأولوية</Label><select name="priority" className={inputClass} defaultValue="medium"><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div>{prefillCase ? (<>
            <input type="hidden" name="case" value={prefillCase.id} />
            <div className="space-y-2"><Label>القضية</Label><div className="h-10 rounded-lg bg-[#edf4f1] text-[#1b6258] px-3 flex items-center gap-2 text-sm font-semibold"><span className="truncate">{prefillCase.case_number}</span><span className="mr-auto text-[11px] font-normal shrink-0">مرتبطة تلقائياً</span></div></div>
            </>) : (<div className="space-y-2"><Label>القضية</Label><select name="case" className={inputClass} defaultValue={prefillCaseId}><option value="">مهمة عامة</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number}</option>)}</select></div>)}<div className="space-y-2"><Label>الموعد</Label><Input name="due" type="datetime-local" defaultValue={dateValue(2)} /></div><div className="sm:col-span-2 space-y-2"><Label>التفاصيل</Label><Textarea name="description" /></div><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">إنشاء المهمة</Button></div></form></Modal>}
  {modal === 'doc' && <Modal title="رفع مستند" onClose={() => setModal(null)}><form className="grid sm:grid-cols-2 gap-4" onSubmit={e => add('doc', e)}><div className="sm:col-span-2 space-y-2"><Label>الملف</Label><Input name="file" type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" required /></div><div className="space-y-2"><Label>التصنيف</Label><select name="category" className={inputClass}><option value="court_filing">مذكرة قضائية</option><option value="power_of_attorney">وكالة</option><option value="contract">عقد</option><option value="evidence">دليل</option><option value="identity">هوية</option><option value="memo">مذكرة</option><option value="other">أخرى</option></select></div>{prefillCase ? (<>
            <input type="hidden" name="case" value={prefillCase.id} />
            <div className="space-y-2"><Label>القضية</Label><div className="h-10 rounded-lg bg-[#edf4f1] text-[#1b6258] px-3 flex items-center gap-2 text-sm font-semibold"><span className="truncate">{prefillCase.case_number}</span><span className="mr-auto text-[11px] font-normal shrink-0">مرتبطة تلقائياً</span></div></div>
            </>) : (<div className="space-y-2"><Label>القضية</Label><select name="case" className={inputClass} defaultValue={prefillCaseId}><option value="">غير مرتبط</option>{cases.map(item => <option key={item.id} value={item.id}>{item.case_number}</option>)}</select></div>)}{prefillCase && prefillClientId ? (<>
            <input type="hidden" name="client" value={prefillClientId} />
            <div className="sm:col-span-2 space-y-2"><Label>العميل (مشتق من القضية)</Label><div className="h-10 rounded-lg bg-[#f4f7f5] text-[#153a36] px-3 flex items-center gap-2 text-sm font-semibold"><span className="truncate">{prefillClientName}</span><span className="mr-auto text-[11px] font-normal shrink-0">يُربط تلقائياً بعميل القضية</span></div></div>
            </>) : (<div className="sm:col-span-2 space-y-2"><Label>العميل</Label><select name="client" className={inputClass}><option value="">غير مرتبط</option>{clients.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></div>)}<p className="sm:col-span-2 text-xs text-muted-foreground">يجب ربط المستند بقضية أو عميل. التخزين خاص بالمكتب.</p><div className="sm:col-span-2 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">رفع المستند</Button></div></form></Modal>}
  {modal === 'invite' && <Modal title="دعوة عضو إلى المكتب" onClose={() => setModal(null)}><form className="space-y-4" onSubmit={e => add('invite', e)}><div className="space-y-2"><Label>البريد الإلكتروني</Label><Input name="email" type="email" dir="ltr" required /></div><div className="space-y-2"><Label>الدور</Label><select name="role" className={inputClass}><option value="lawyer">محامٍ</option><option value="employee">موظف</option></select></div><p className="text-xs text-muted-foreground">سيتم إنشاء رابط دعوة فريد ونسخه للحافظة لمشاركته مع العضو.</p><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setModal(null)}>إلغاء</Button><Button className="bg-[#0d3b36]">إنشاء رابط الدعوة</Button></div></form></Modal>}
  </AppShell>;
}
