import { supabase } from '@/lib/supabase';
import InvoiceManager from '@/components/InvoiceManager';
import RecurringBillingManager from '@/components/RecurringBillingManager';
import PlatformOperations, { type Brand, type OpsAlert, type OpsAudit, type OpsEvent, type OpsInvitation, type OpsInvoice, type OpsOffice, type OpsPlan, type OpsProfile, type OpsSubscription, type OpsTicket, type OpsTicketMessage } from '@/components/PlatformOperations';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { BellRing, Building2, CalendarClock, ChartNoAxesCombined, CircleDollarSign, Crown, FileSearch, LayoutDashboard, LifeBuoy, Loader2, Palette, PauseCircle, PlayCircle, ReceiptText, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Link } from 'wouter';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

type Section = 'overview'|'offices'|'invoices'|'recurring'|'users'|'audit'|'alerts'|'plans'|'analytics'|'support'|'brand';
type Subscription = { id:string; office_id:string; plan_id:string; status:string; current_period_ends_at:string|null; saas_plans:OpsPlan|OpsPlan[]|null };
const sections:{id:Section;label:string;icon:typeof LayoutDashboard;group:'core'|'ops'}[]=[
  {id:'overview',label:'نظرة عامة',icon:LayoutDashboard,group:'core'},{id:'offices',label:'المكاتب',icon:Building2,group:'core'},{id:'invoices',label:'الفواتير',icon:ReceiptText,group:'core'},{id:'recurring',label:'التجديدات',icon:CalendarClock,group:'core'},{id:'users',label:'المستخدمون',icon:Users,group:'core'},
  {id:'audit',label:'سجل التدقيق',icon:FileSearch,group:'ops'},{id:'alerts',label:'التنبيهات',icon:BellRing,group:'ops'},{id:'plans',label:'الخطط',icon:Sparkles,group:'ops'},{id:'analytics',label:'التحليلات',icon:ChartNoAxesCombined,group:'ops'},{id:'support',label:'الدعم',icon:LifeBuoy,group:'ops'},{id:'brand',label:'العلامة التجارية',icon:Palette,group:'ops'}
];
const statusLabel:Record<string,string>={active:'نشط',trial:'تجربة',suspended:'معلّق',trialing:'تجربة',cancelled:'ملغى',past_due:'متأخر'};
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat('ar-QA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v)):'—';
const planOf=(plan:Subscription['saas_plans'])=>Array.isArray(plan)?plan[0]:plan;

function Layout({section,children}:{section:Section;children:React.ReactNode}){const items=(group:'core'|'ops')=>sections.filter(x=>x.group===group).map(item=>{const I=item.icon;return <Link key={item.id} href={`/platform/${item.id}`} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm ${section===item.id?'bg-[#e8c377] text-[#153a36] font-bold':'text-emerald-50 hover:bg-white/10'}`}><I className="h-4 w-4"/>{item.label}</Link>});return <main dir="rtl" className="min-h-screen bg-[#f4f7f5] text-foreground lg:pr-70"><aside className="hidden lg:flex fixed inset-y-0 right-0 z-30 w-70 flex-col bg-[#103b35] text-white overflow-y-auto"><div className="p-7 border-b border-white/10"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8c377] text-[#153a36]"><Crown className="h-5 w-5"/></span><div><p className="text-xs text-emerald-100/70">منصة ميزان المكتب</p><p className="font-bold">Super Admin</p></div></div></div><nav className="p-4 space-y-1">{items('core')}<p className="pt-5 pb-2 px-3 text-[10px] font-bold tracking-[.15em] text-emerald-100/45">العمليات والمنصة</p>{items('ops')}</nav><div className="mt-auto m-4 rounded-xl border border-white/10 p-4 text-xs leading-6 text-emerald-100/65">وصول مركزي محكوم لإدارة المنصة دون كشف ملفات العملاء أو القضايا.</div></aside><nav className="lg:hidden sticky top-0 z-30 flex gap-2 overflow-x-auto bg-[#103b35] px-4 py-3">{sections.map(item=><Link key={item.id} href={`/platform/${item.id}`} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${section===item.id?'bg-[#e8c377] text-[#153a36] font-bold':'bg-white/10 text-white'}`}>{item.label}</Link>)}</nav><header className="bg-[#103b35] text-white"><div className="max-w-7xl mx-auto px-5 py-7"><p className="text-xs text-emerald-100/70">مركز تحكم SaaS</p><h1 className="mt-2 text-2xl font-bold">إدارة المنصة المركزية</h1></div></header><div className="max-w-7xl mx-auto px-5 py-8">{children}</div></main>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="mb-6"><p className="text-[11px] tracking-[.15em] font-bold text-[#b58524]">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-[#153a36]">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>}

export default function PlatformPages({adminId,section}:{adminId:string;section:Section}){
  const [offices,setOffices]=useState<OpsOffice[]>([]);const [plans,setPlans]=useState<OpsPlan[]>([]);const [subs,setSubs]=useState<Subscription[]>([]);const [profiles,setProfiles]=useState<OpsProfile[]>([]);const [audits,setAudits]=useState<OpsAudit[]>([]);const [alerts,setAlerts]=useState<OpsAlert[]>([]);const [invoices,setInvoices]=useState<OpsInvoice[]>([]);const [events,setEvents]=useState<OpsEvent[]>([]);const [tickets,setTickets]=useState<OpsTicket[]>([]);const [ticketMessages,setTicketMessages]=useState<OpsTicketMessage[]>([]);const [invitations,setInvitations]=useState<OpsInvitation[]>([]);const [brand,setBrand]=useState<Brand|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);
  const load=async()=>{setLoading(true);const [a,b,c,d,e,f,g,h,i,j,k,l,m]=await Promise.all([
    supabase.from('offices').select('id,name,email,phone,address').order('created_at',{ascending:false}),
    supabase.from('saas_plans').select('id,code,name_ar,description_ar,monthly_price_qar,annual_price_qar,max_users,max_cases,ai_monthly_requests,features,is_active,sort_order').order('sort_order'),
    supabase.from('office_subscriptions').select('id,office_id,plan_id,status,current_period_ends_at,saas_plans(id,code,name_ar,description_ar,monthly_price_qar,annual_price_qar,max_users,max_cases,ai_monthly_requests,features,is_active,sort_order)'),
    supabase.from('profiles').select('id,office_id,display_name,email,role,is_active,created_at').order('created_at',{ascending:false}),
    supabase.from('platform_audit_logs').select('id,action,office_id,actor_id,metadata,created_at').order('created_at',{ascending:false}).limit(100),
    supabase.from('platform_notifications').select('id,category,severity,title_ar,body_ar,office_id,read_at,created_at').order('created_at',{ascending:false}).limit(100),
    supabase.from('saas_invoices').select('id,office_id,total_amount,status,created_at').order('created_at',{ascending:false}).limit(250),
    supabase.from('platform_subscription_events').select('id,office_id,event_type,created_at').order('created_at',{ascending:false}).limit(250),
    supabase.from('support_tickets').select('id,office_id,subject,category,priority,status,opened_by,created_at,last_activity_at').order('last_activity_at',{ascending:false}),
    supabase.from('platform_brand_settings').select('app_name,legal_name,logo_url,support_email,support_phone,invoice_footer,primary_contact_name,message_templates').maybeSingle(),
    supabase.from('platform_admins').select('user_id').eq('user_id',adminId).maybeSingle(),
    supabase.from('office_invitations').select('id,office_id,email,role,invitation_token,expires_at,accepted_at').order('expires_at',{ascending:true}),
    supabase.from('support_ticket_messages').select('id,ticket_id,author_id,body,is_internal,created_at').order('created_at',{ascending:true})
  ]);if([a,b,c,d,e,f,g,h,i,j,k,l].some(x=>x.error))toast.error('تعذر تحميل جزء من بيانات المنصة.');setOffices((a.data??[]) as OpsOffice[]);setPlans((b.data??[]) as OpsPlan[]);setSubs((c.data??[]) as Subscription[]);setProfiles((d.data??[]) as OpsProfile[]);setAudits((e.data??[]) as OpsAudit[]);setAlerts((f.data??[]) as OpsAlert[]);setInvoices((g.data??[]) as OpsInvoice[]);setEvents((h.data??[]) as OpsEvent[]);setTickets((i.data??[]) as OpsTicket[]);setBrand((j.data??null) as Brand|null);setInvitations((l.data??[]) as OpsInvitation[]);setTicketMessages((m.data??[]) as OpsTicketMessage[]);setLoading(false)};
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>({offices:offices.length,active:subs.filter(s=>['active','trialing'].includes(s.status)).length,users:profiles.filter(p=>p.is_active).length,paid:subs.filter(s=>s.status==='active').length}),[offices,subs,profiles]);
  const audit=(action:string,office_id:string|null,metadata:Record<string,unknown>)=>supabase.from('platform_audit_logs').insert({actor_id:adminId,action,office_id,metadata});
  const setService=async(o:OpsOffice,next:'active'|'suspended')=>{setBusy(o.id);const{error}=await supabase.from('offices').update({service_status:next,service_status_changed_at:new Date().toISOString()}).eq('id',o.id);if(error)toast.error(error.message);else{await audit(next==='active'?'office_activated':'office_suspended',o.id,{});toast.success('تم تحديث حالة المكتب.');await load()}setBusy(null)};
  const setPlan=async(officeId:string,planId:string)=>{const{error}=await supabase.from('office_subscriptions').update({plan_id:planId,updated_by:adminId}).eq('office_id',officeId);if(error)toast.error(error.message);else{await audit('subscription_plan_changed',officeId,{planId});toast.success('تم تحديث الخطة.');await load()}};
  if(loading)return <main className="min-h-screen grid place-items-center bg-[#f4f7f5]"><Loader2 className="h-7 w-7 animate-spin text-[#1b6258]"/></main>;
  const ops=()=> <PlatformOperations mode={section as 'audit'|'alerts'|'plans'|'analytics'|'support'|'brand'|'users'} adminId={adminId} offices={offices} plans={plans} subscriptions={subs as OpsSubscription[]} profiles={profiles} audits={audits} alerts={alerts} invoices={invoices} events={events} tickets={tickets} ticketMessages={ticketMessages} invitations={invitations} brand={brand} onRefresh={load}/>;
  if(section==='overview')return <Layout section={section}><Heading eyebrow="ملخص تشغيلي" title="حالة المنصة في لمحة" text="تابع صحة المكاتب والاشتراكات والتنبيهات من مساحة مركزية واحدة."/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[{t:'المكاتب المسجلة',v:stats.offices,i:Building2,c:'bg-blue-50 text-blue-700'},{t:'اشتراكات تشغيلية',v:stats.active,i:ShieldCheck,c:'bg-emerald-50 text-emerald-700'},{t:'مستخدمون نشطون',v:stats.users,i:Users,c:'bg-violet-50 text-violet-700'},{t:'اشتراكات مدفوعة',v:stats.paid,i:CircleDollarSign,c:'bg-amber-50 text-amber-700'}].map(x=>{const I=x.i;return <Card key={x.t} className="border-0 shadow-sm"><CardContent className="p-5 flex justify-between"><div><p className="text-sm text-muted-foreground">{x.t}</p><p className="mt-2 text-3xl font-bold text-[#153a36]">{x.v}</p></div><span className={`grid h-11 w-11 place-items-center rounded-xl ${x.c}`}><I className="h-5 w-5"/></span></CardContent></Card>})}</div>{alerts.filter(x=>!x.read_at).slice(0,3).length>0&&<Card className="border-0 shadow-sm mt-6"><CardHeader><CardTitle className="flex gap-2"><BellRing className="h-5 w-5 text-[#b58524]"/>تنبيهات تحتاج مراجعة</CardTitle></CardHeader><CardContent className="space-y-2">{alerts.filter(x=>!x.read_at).slice(0,3).map(x=><p key={x.id} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{x.title_ar}: {x.body_ar}</p>)}</CardContent></Card>}</Layout>;
  if(section==='offices')return <Layout section={section}><Heading eyebrow="المكاتب والاشتراكات" title="إدارة الخدمة والخطط" text="حدّث حالة المكتب وخطة اشتراكه من صفحة مستقلة."/><Card className="border-0 shadow-sm overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#edf4f1]"><tr>{['المكتب','الحالة','الخطة','الاستحقاق','إدارة'].map(x=><th className="p-4 text-right font-medium" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{offices.map(o=>{const s=subs.find(x=>x.office_id===o.id),p=s?planOf(s.saas_plans):null;return <tr key={o.id}><td className="p-4 font-semibold text-[#153a36]">{o.name}</td><td className="p-4"><Badge variant="outline">{statusLabel[s?.status??'']||s?.status||'—'}</Badge></td><td className="p-4">{s?<Select value={s.plan_id} onValueChange={v=>setPlan(o.id,v)}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent>{plans.filter(p=>p.is_active).map(p=><SelectItem key={p.id} value={p.id}>{p.name_ar}</SelectItem>)}</SelectContent></Select>:p?.name_ar||'—'}</td><td className="p-4 text-muted-foreground">{fmt(s?.current_period_ends_at)}</td><td className="p-4"><Button size="sm" variant="outline" disabled={busy===o.id} onClick={()=>setService(o,'suspended')} className="text-rose-700"><PauseCircle className="h-4 w-4"/>تعليق</Button><Button size="sm" disabled={busy===o.id} onClick={()=>setService(o,'active')} className="mr-2 bg-[#0d3b36]"><PlayCircle className="h-4 w-4"/>تفعيل</Button></td></tr>})}</tbody></table></div></CardContent></Card></Layout>;
  if(section==='invoices')return <Layout section={section}><Heading eyebrow="الفوترة" title="الفواتير الضريبية" text="إنشاء الفواتير ومراجعة حالات التحصيل."/><InvoiceManager adminId={adminId} offices={offices}/></Layout>;
  if(section==='recurring')return <Layout section={section}><Heading eyebrow="التجديدات" title="الفوترة الدورية" text="إدارة دورات التجديد وتشغيل المسودات عند الحاجة."/><RecurringBillingManager adminId={adminId}/></Layout>;
  const map:Record<string,{eyebrow:string;title:string;text:string}>={users:{eyebrow:'الحسابات',title:'إدارة المستخدمين الموسعة',text:'الأدوار والحالة وروابط إعادة التعيين.'},audit:{eyebrow:'الحوكمة',title:'سجل التدقيق',text:'بحث وتصدير إجراءات المنصة.'},alerts:{eyebrow:'التشغيل',title:'مركز التنبيهات',text:'التجارب والمدفوعات والتجديدات التي تتطلب إجراء.'},plans:{eyebrow:'المنتج',title:'إدارة الخطط',text:'إنشاء وتفعيل وإيقاف خطط SaaS وحدودها.'},analytics:{eyebrow:'القياس',title:'تحليلات SaaS',text:'مؤشرات الإيراد والاشتراكات والأحداث.'},support:{eyebrow:'الدعم',title:'مركز الدعم',text:'تذاكر المكاتب والملاحظات الداخلية.'},brand:{eyebrow:'الهوية',title:'العلامة التجارية',text:'بيانات المنصة والفاتورة والتواصل.'}};
  const content=map[section]??map.users;return <Layout section={section}><Heading {...content}/>{ops()}</Layout>
}
