import { supabase } from '@/lib/supabase';
import InvoiceManager from '@/components/InvoiceManager';
import RecurringBillingManager from '@/components/RecurringBillingManager';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Building2, CalendarClock, CircleDollarSign, Crown, LayoutDashboard, Loader2, PauseCircle, PlayCircle, ReceiptText, ShieldCheck, UserCheck, UserRoundCog, UserX, Users } from 'lucide-react';
import { Link } from 'wouter';
import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

type Plan = { id:string; code:string; name_ar:string; monthly_price_qar:number|null; max_users:number|null; is_active:boolean };
type Subscription = { id:string; office_id:string; plan_id:string; status:string; current_period_ends_at:string|null; saas_plans:Plan|Plan[]|null };
type Office = { id:string; name:string; email:string|null; phone:string|null; address:string|null; service_status:string; created_at:string };
type Profile = { id:string; office_id:string|null; is_active:boolean; display_name:string; email:string|null; role:string; created_at:string };
type Section = 'overview'|'offices'|'invoices'|'recurring'|'users';
const sections: {id:Section;label:string;icon:typeof LayoutDashboard}[] = [{id:'overview',label:'نظرة عامة',icon:LayoutDashboard},{id:'offices',label:'المكاتب',icon:Building2},{id:'invoices',label:'الفواتير',icon:ReceiptText},{id:'recurring',label:'التجديدات',icon:CalendarClock},{id:'users',label:'المستخدمون',icon:UserRoundCog}];
const labels:Record<string,string>={active:'نشط',trial:'تجربة',suspended:'معلّق',trialing:'تجربة',cancelled:'ملغى'};
const roleLabel:Record<string,string>={manager:'مدير المكتب',lawyer:'محامٍ',employee:'موظف'};
const fmt=(v?:string|null)=>v?new Intl.DateTimeFormat('ar-QA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v)):'—';
const planOf=(p:Subscription['saas_plans'])=>Array.isArray(p)?p[0]:p;

function Layout({section,children}:{section:Section;children:React.ReactNode}) { return <main dir="rtl" className="min-h-screen bg-[#f4f7f5] text-foreground lg:pr-70"><aside className="hidden lg:flex fixed inset-y-0 right-0 z-30 w-70 flex-col bg-[#103b35] text-white"><div className="p-7 border-b border-white/10"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8c377] text-[#153a36]"><Crown className="h-5 w-5"/></span><div><p className="text-xs text-emerald-100/70">منصة ميزان المكتب</p><p className="font-bold">Super Admin</p></div></div></div><nav className="p-4 space-y-1">{sections.map(item=>{const Icon=item.icon;return <Link key={item.id} href={`/platform/${item.id}`} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm ${section===item.id?'bg-[#e8c377] text-[#153a36] font-bold':'text-emerald-50 hover:bg-white/10'}`}><Icon className="h-4 w-4"/>{item.label}</Link>})}</nav><div className="mt-auto m-4 rounded-xl border border-white/10 p-4 text-xs leading-6 text-emerald-100/65">وصول مركزي آمن لإدارة المنصة دون كشف ملفات العملاء أو القضايا.</div></aside><nav className="lg:hidden sticky top-0 z-30 flex gap-2 overflow-x-auto bg-[#103b35] px-4 py-3">{sections.map(item=><Link key={item.id} href={`/platform/${item.id}`} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${section===item.id?'bg-[#e8c377] text-[#153a36] font-bold':'bg-white/10 text-white'}`}>{item.label}</Link>)}</nav><header className="bg-[#103b35] text-white"><div className="max-w-7xl mx-auto px-5 py-7"><p className="text-xs text-emerald-100/70">مركز تحكم SaaS</p><h1 className="mt-2 text-2xl font-bold">إدارة المنصة المركزية</h1></div></header><div className="max-w-7xl mx-auto px-5 py-8">{children}</div></main>; }
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) {return <div className="mb-6"><p className="text-[11px] tracking-[.15em] font-bold text-[#b58524]">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-[#153a36]">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>}

export default function PlatformPages({adminId,section}:{adminId:string;section:Section}) {
  const [offices,setOffices]=useState<Office[]>([]); const [plans,setPlans]=useState<Plan[]>([]); const [subs,setSubs]=useState<Subscription[]>([]); const [profiles,setProfiles]=useState<Profile[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
  const load=async()=>{setLoading(true);const[a,b,c,d]=await Promise.all([supabase.from('offices').select('id,name,email,phone,address,service_status,created_at').order('created_at',{ascending:false}),supabase.from('saas_plans').select('id,code,name_ar,monthly_price_qar,max_users,is_active').order('sort_order'),supabase.from('office_subscriptions').select('id,office_id,plan_id,status,current_period_ends_at,saas_plans(id,code,name_ar,monthly_price_qar,max_users,is_active)'),supabase.from('profiles').select('id,office_id,is_active,display_name,email,role,created_at').order('created_at',{ascending:false})]);setOffices((a.data??[]) as Office[]);setPlans((b.data??[]) as Plan[]);setSubs((c.data??[]) as Subscription[]);setProfiles((d.data??[]) as Profile[]);if(a.error||b.error||c.error||d.error)toast.error('تعذر تحميل بيانات المنصة.');setLoading(false)};
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>({offices:offices.length,active:offices.filter(o=>['active','trial'].includes(o.service_status)).length,users:profiles.filter(p=>p.is_active).length,paid:subs.filter(s=>s.status==='active').length}),[offices,profiles,subs]);
  const audit=(action:string,office_id:string|null,metadata:Record<string,unknown>)=>supabase.from('platform_audit_logs').insert({actor_id:adminId,action,office_id,metadata});
  const setService=async(o:Office,next:'active'|'suspended')=>{setBusy(o.id);const{error}=await supabase.from('offices').update({service_status:next,service_status_changed_at:new Date().toISOString()}).eq('id',o.id);if(error)toast.error(error.message);else{await audit(next==='active'?'office_activated':'office_suspended',o.id,{});toast.success(next==='active'?'تم تفعيل المكتب.':'تم تعليق المكتب.');load()}setBusy(null)};
  const setPlan=async(officeId:string,planId:string)=>{const{error}=await supabase.from('office_subscriptions').update({plan_id:planId,updated_by:adminId}).eq('office_id',officeId);if(error)toast.error(error.message);else{await audit('subscription_plan_changed',officeId,{planId});toast.success('تم تحديث الخطة.');load()}};
  const setUser=async(p:Profile,next:boolean)=>{if(p.id===adminId)return toast.error('لا يمكن تعطيل حساب Super Admin الحالي.');setBusy(p.id);const{error}=await supabase.from('profiles').update({is_active:next}).eq('id',p.id);if(error)toast.error(error.message);else{await audit(next?'user_activated':'user_deactivated',p.office_id,{userId:p.id});toast.success(next?'تم تفعيل المستخدم.':'تم تعطيل المستخدم.');load()}setBusy(null)};
  if(loading)return <main className="min-h-screen grid place-items-center bg-[#f4f7f5]"><Loader2 className="h-7 w-7 animate-spin text-[#1b6258]"/></main>;
  if(section==='overview')return <Layout section={section}><Heading eyebrow="ملخص تشغيلي" title="حالة المنصة في لمحة" text="تابع صحة الخدمة والمكاتب والحسابات من صفحة واحدة مختصرة."/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[{t:'المكاتب المسجلة',v:stats.offices,i:Building2,c:'bg-blue-50 text-blue-700'},{t:'مكاتب تشغيلية',v:stats.active,i:ShieldCheck,c:'bg-emerald-50 text-emerald-700'},{t:'مستخدمون نشطون',v:stats.users,i:Users,c:'bg-violet-50 text-violet-700'},{t:'اشتراكات مدفوعة',v:stats.paid,i:CircleDollarSign,c:'bg-amber-50 text-amber-700'}].map(x=>{const I=x.i;return <Card key={x.t} className="border-0 shadow-sm"><CardContent className="p-5 flex justify-between"><div><p className="text-sm text-muted-foreground">{x.t}</p><p className="mt-2 text-3xl font-bold text-[#153a36]">{x.v}</p></div><span className={`grid h-11 w-11 place-items-center rounded-xl ${x.c}`}><I className="h-5 w-5"/></span></CardContent></Card>})}</div><Card className="border-0 shadow-sm mt-6 bg-[#103b35] text-white"><CardContent className="p-6"><p className="text-[#e8c377] text-sm">اختصارات الإدارة</p><p className="mt-2 text-lg font-bold">اختر قسماً من الشريط الجانبي لإدارة المكاتب أو الفواتير أو المستخدمين.</p></CardContent></Card></Layout>;
  if(section==='offices')return <Layout section={section}><Heading eyebrow="المكاتب والاشتراكات" title="إدارة الخدمة والخطط" text="حدّث حالة المكتب وخطة اشتراكه من صفحة مستقلة."/><div className="grid xl:grid-cols-[1.55fr_.45fr] gap-5"><Card className="border-0 shadow-sm overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#edf4f1]"><tr>{['المكتب','الخدمة','الخطة','المستخدمون','الاستحقاق','إدارة'].map(x=><th className="p-4 text-right font-medium" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{offices.map(o=>{const s=subs.find(x=>x.office_id===o.id),p=s?planOf(s.saas_plans):null,n=profiles.filter(x=>x.office_id===o.id&&x.is_active).length;return <tr key={o.id}><td className="p-4"><p className="font-semibold text-[#153a36]">{o.name}</p><p className="text-xs text-muted-foreground mt-1" dir="ltr">{o.email||o.phone||'—'}</p></td><td className="p-4"><Badge variant="outline">{labels[o.service_status]||o.service_status}</Badge></td><td className="p-4">{s?<Select value={s.plan_id} onValueChange={v=>setPlan(o.id,v)}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent>{plans.filter(p=>p.is_active).map(p=><SelectItem key={p.id} value={p.id}>{p.name_ar}</SelectItem>)}</SelectContent></Select>:'—'}</td><td className="p-4">{n}{p?.max_users?` / ${p.max_users}`:''}</td><td className="p-4 text-muted-foreground">{fmt(s?.current_period_ends_at)}</td><td className="p-4">{o.service_status==='suspended'?<Button size="sm" disabled={busy===o.id} onClick={()=>setService(o,'active')} className="bg-[#0d3b36]"><PlayCircle className="h-4 w-4"/>تفعيل</Button>:<Button size="sm" variant="outline" disabled={busy===o.id} onClick={()=>setService(o,'suspended')} className="text-rose-700"><PauseCircle className="h-4 w-4"/>تعليق</Button>}</td></tr>})}</tbody></table></div></CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle>الخطط المتاحة</CardTitle><CardDescription>أسعار وحدود الخطط الحالية.</CardDescription></CardHeader><CardContent className="space-y-3">{plans.map(p=><div key={p.id} className="border rounded-xl p-4"><p className="font-semibold text-[#153a36]">{p.name_ar}</p><p className="text-sm text-muted-foreground mt-1">{p.monthly_price_qar?`${p.monthly_price_qar} ر.ق شهرياً`:'تسعير مخصص'}</p></div>)}</CardContent></Card></div></Layout>;
  if(section==='invoices')return <Layout section={section}><Heading eyebrow="الفوترة" title="الفواتير الضريبية" text="إصدار الفواتير ومراجعة حالات التحصيل."/><InvoiceManager adminId={adminId} offices={offices}/></Layout>;
  if(section==='recurring')return <Layout section={section}><Heading eyebrow="التجديدات" title="الفوترة الدورية" text="إدارة دورات التجديد وتشغيل المسودات عند الحاجة."/><RecurringBillingManager adminId={adminId}/></Layout>;
  return <Layout section="users"><Heading eyebrow="الحسابات" title="إدارة المستخدمين" text="تفعيل وتعطيل حسابات المكاتب من صفحة مستقلة."/><Card className="border-0 shadow-sm overflow-hidden"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-[#edf4f1]"><tr>{['المستخدم','الدور','المكتب','الحالة','الانضمام','إجراء'].map(x=><th className="p-4 text-right font-medium" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{profiles.map(p=>{const o=offices.find(x=>x.id===p.office_id);return <tr key={p.id}><td className="p-4"><p className="font-semibold text-[#153a36]">{p.display_name||'مستخدم جديد'}</p><p className="text-xs text-muted-foreground mt-1" dir="ltr">{p.email||p.id}</p></td><td className="p-4"><Badge variant="outline">{roleLabel[p.role]||'منصة'}</Badge></td><td className="p-4 text-muted-foreground">{o?.name||'حساب المنصة'}</td><td className="p-4"><Badge variant="outline">{p.is_active?'مفعّل':'معطّل'}</Badge></td><td className="p-4 text-muted-foreground">{fmt(p.created_at)}</td><td className="p-4">{p.id===adminId?<span className="text-xs text-muted-foreground">الحساب الحالي</span>:p.is_active?<Button size="sm" variant="outline" disabled={busy===p.id} onClick={()=>setUser(p,false)} className="text-rose-700"><UserX className="h-4 w-4"/>تعطيل</Button>:<Button size="sm" disabled={busy===p.id} onClick={()=>setUser(p,true)} className="bg-[#0d3b36]"><UserCheck className="h-4 w-4"/>تفعيل</Button>}</td></tr>})}</tbody></table></div></CardContent></Card></Layout>;
}
