import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { CalendarClock, Loader2, RefreshCw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';

type Subscription = { id: string; office_id: string; billing_cycle: 'monthly' | 'annual' | 'manual'; next_billing_at: string | null; recurring_billing_enabled: boolean; offices: { name: string } | { name: string }[] | null; saas_plans: { name_ar: string } | { name_ar: string }[] | null };
type Cycle = { id: string; generated_at: string; period_starts_at: string; period_ends_at: string; office_id: string; saas_invoices: { invoice_number: string } | { invoice_number: string }[] | null; offices: { name: string } | { name: string }[] | null };
const unwrap = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] ?? null : value;
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('ar-QA', { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)) : '—';

export default function RecurringBillingManager({ adminId }: { adminId: string }) {
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [cycles, setCycles] = useState<Cycle[]>([]); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false);
  const load = async () => { setLoading(true); const [s, c] = await Promise.all([supabase.from('office_subscriptions').select('id,office_id,billing_cycle,next_billing_at,recurring_billing_enabled,offices(name),saas_plans(name_ar)').in('billing_cycle', ['monthly', 'annual']).order('next_billing_at'), supabase.from('subscription_billing_cycles').select('id,generated_at,period_starts_at,period_ends_at,office_id,offices(name),saas_invoices(invoice_number)').order('generated_at', { ascending: false }).limit(8)]); if (s.error || c.error) toast.error('تعذر تحميل دورات الفوترة.'); setSubscriptions((s.data ?? []) as Subscription[]); setCycles((c.data ?? []) as Cycle[]); setLoading(false); };
  useEffect(() => { load(); }, []);
  const update = async (subscription: Subscription, values: Partial<Subscription>) => { const { error } = await supabase.from('office_subscriptions').update(values).eq('id', subscription.id); if (error) toast.error(error.message); else { await supabase.from('platform_audit_logs').insert({ actor_id: adminId, action: 'recurring_billing_updated', office_id: subscription.office_id, metadata: values }); toast.success('تم حفظ إعدادات التجديد.'); await load(); } };
  const run = async () => { setRunning(true); const { data, error } = await supabase.rpc('run_recurring_billing_manual'); if (error) toast.error(error.message); else { toast.success(`تم إنشاء ${data?.created ?? 0} مسودة تجديد مستحقة.`); await load(); } setRunning(false); };
  if (loading) return <Card className="border-0 shadow-sm mt-6"><CardContent className="p-8 grid place-items-center"><Loader2 className="animate-spin h-5 w-5 text-[#1b6258]" /></CardContent></Card>;
  return <Card className="border-0 shadow-sm mt-6" dir="rtl"><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="text-xl text-[#153a36] flex gap-2 items-center"><CalendarClock className="h-5 w-5 text-[#b58524]" />الفوترة الدورية</CardTitle><CardDescription>تنشئ المنصة مسودة تجديد واحدة لكل اشتراك وفترة، ثم تراجع وتُعتمد من لوحة الفواتير.</CardDescription></div><Button disabled={running} onClick={run} className="bg-[#0d3b36]">{running ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}تشغيل التجديد الآن</Button></CardHeader><CardContent className="space-y-6"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#edf4f1] text-muted-foreground"><tr>{['المكتب', 'الخطة', 'الدورة', 'موعد التجديد', 'مفعّل'].map(h => <th className="p-3 text-right font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{subscriptions.map(s => <tr key={s.id}><td className="p-3 font-semibold text-[#153a36]">{unwrap(s.offices)?.name || '—'}</td><td className="p-3">{unwrap(s.saas_plans)?.name_ar || '—'}</td><td className="p-3"><select value={s.billing_cycle} className="h-9 rounded-md border bg-white px-2" onChange={e => update(s, { billing_cycle: e.target.value as Subscription['billing_cycle'] })}><option value="monthly">شهري</option><option value="annual">سنوي</option></select></td><td className="p-3"><Input type="date" className="w-40" value={s.next_billing_at ? s.next_billing_at.slice(0, 10) : ''} onChange={e => update(s, { next_billing_at: e.target.value ? new Date(e.target.value).toISOString() : null })} /></td><td className="p-3"><input aria-label="تفعيل التجديد" type="checkbox" checked={s.recurring_billing_enabled} onChange={e => update(s, { recurring_billing_enabled: e.target.checked })} /></td></tr>)}</tbody></table></div><div><p className="font-semibold text-[#153a36] mb-3">آخر المسودات المولدة</p><div className="space-y-2">{cycles.map(c => <div key={c.id} className="rounded-lg border bg-[#f8fbfa] p-3 text-sm flex flex-wrap gap-x-3 gap-y-1"><b>{unwrap(c.offices)?.name || 'مكتب'}</b><span>{unwrap(c.saas_invoices)?.invoice_number || 'مسودة'}</span><span className="text-muted-foreground">{formatDate(c.period_starts_at)} — {formatDate(c.period_ends_at)}</span></div>)}{cycles.length === 0 && <p className="text-sm text-muted-foreground">لا توجد دورات مولدة بعد.</p>}</div></div></CardContent></Card>;
}
